### ISSUE TITLE
add Neo4j

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#33]
### Add store - Neo4j

- [x] Add implementation for the interface [DB](https://github.com/batazor/shortlink/blob/84fa2a365f09396f92556febde2e711c1682a780/internal/pkg/db/type.go#L9)
https://github.com/batazor/shortlink/blob/84fa2a365f09396f92556febde2e711c1682a780/internal/pkg/db/type.go#L9
- [x] Add option of switcher https://github.com/batazor/shortlink/blob/84fa2a365f09396f92556febde2e711c1682a780/internal/pkg/db/db.go#L27
- [x] Add implementation for the interface of Repository (optional)https://github.com/batazor/shortlink/blob/84fa2a365f09396f92556febde2e711c1682a780/internal/services/link/infrastructure/store/crud/type.go#L13
- [x] Add tests ([simple example](https://github.com/batazor/shortlink/blob/main/internal/pkg/db/mongo/mongo_test.go))

**Comment by JigarJoshi04** [comment]
Can there be more context given on exactly what functionalities are required for the Neo4j.
I am ready to pick this up.
But need more context on what kind of development is needed

**Comment by batazor** [comment]
Hi @JigarJoshi04 🤝 . Sorry for the long reply, and thanks so much for your interest!

I've updated the task description, first of all, it would be nice to add a connector for this database (1 point of the task) and add a simple test that will run it and check connectivity to it. As an example, you can see the test in mongodb or postgres.
